server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  # 路由
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启动态路由，通过微服务名称进行路由
      routes:
        - id: payment_routh # 路由id 保证唯一，一般用 spring.application.name
          # uri: http://localhost:9001 # 匹配后提供服务的地址
          uri: lb://CLOUD-PROVIDE-PAYMENT # 匹配后提供服务的地址
          predicates:
            - Path=/payment/getPaymentById/** # 断言，路径相匹配进行路由
            - After=2021-11-24T11:06:34.682+08:00[Asia/Shanghai]
            # - Before=2021-11-24T11:06:34.682+08:00[Asia/Shanghai]
            # - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
            # - Cookie=wujunjie, 123456

        - id: payment_routh2 # 路由id 保证唯一，一般用 spring.application.name
          # uri: http://localhost:9001 # 匹配后提供服务的地址
          uri: lb://CLOUD-PROVIDE-PAYMENT # 匹配后提供服务的地址
          predicates:
            - Path=/payment/timeout # 断言，路径相匹配进行路由

eureka:
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: true
    # false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
    # 设置 eureka 访问地址
      # defaultZone: http://localhost:7001/eureka/  # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群版
  instance:
    instance-id: bochao9001 # 主机名
    prefer-ip-address: true # 访问路径可以显示 ip 地址

