server:
  port: 9012
spring:
  application:
    name: cloud-nacos-payment
  # nacos
  cloud:
    nacos:
      discovery:
        # server-addr: localhost:8848
        server-addr: 192.168.110.228:1111
# 暴漏所有服务
management:
  endpoints:
    web:
      exposure:
        include: "*"
