server:
  port: 2003
spring:
  application:
    name: seata-account-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver # mysql 驱动包
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group # 自定义事务组名称 与seata-server相对应
    nacos:
      discovery:
        server-addr: localhost:8848
feign:
  hystrix:
    enabled: false
mybatis:
  mapper-locations: classpath:mapper/*
logging:
  level:
    io:
      seata: info
