server:
  port: 9004
spring:
  application:
    name: cloud-provide-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver # mysql 驱动包
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.110.222:2181

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.bochao.entity  # entity 所在地址

